# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install tox
  - pip install coveralls

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pypy
script:
  - tox -e $TOX_ENV
  - coverage run --source=json_config setup.py test
after_success:
  coveralls
