# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install tox --use-mirrors
  - pip install coveralls

env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=docs
script:
  - tox -e $TOXENV
  - coverage run --source=json_config setup.py test
after_success:
  coveralls
