# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install:
  - pip install tox --use-mirrors
  - pip install coveralls

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
script:
  - tox
  - coverage run --source=json_config setup.py test
after_success:
  coveralls
